// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' };
import * as $0 from './routes/_404.tsx';
import * as $1 from './routes/_app.tsx';
import * as $2 from './routes/api/works/[title].ts';
import * as $3 from './routes/api/works/index.ts';
import * as $4 from './routes/index.tsx';
import * as $5 from './routes/works/[title].tsx';
import * as $$0 from './islands/Header.tsx';
import * as $$1 from './islands/Techs.tsx';
import * as $$2 from './islands/Works.tsx';
import * as $$3 from './islands/WorksSection.tsx';

const manifest = {
  routes: {
    './routes/_404.tsx': $0,
    './routes/_app.tsx': $1,
    './routes/api/works/[title].ts': $2,
    './routes/api/works/index.ts': $3,
    './routes/index.tsx': $4,
    './routes/works/[title].tsx': $5,
  },
  islands: {
    './islands/Header.tsx': $$0,
    './islands/Techs.tsx': $$1,
    './islands/Works.tsx': $$2,
    './islands/WorksSection.tsx': $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
