// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_works_title_ from './routes/api/works/[title].ts';
import * as $api_works_index from './routes/api/works/index.ts';
import * as $index from './routes/index.tsx';
import * as $works_title_ from './routes/works/[title].tsx';
import * as $Header from './islands/Header.tsx';
import * as $Techs from './islands/Techs.tsx';
import * as $ThemeToggler from './islands/ThemeToggler.tsx';
import * as $Works from './islands/Works.tsx';
import * as $WorksSection from './islands/WorksSection.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/api/works/[title].ts': $api_works_title_,
    './routes/api/works/index.ts': $api_works_index,
    './routes/index.tsx': $index,
    './routes/works/[title].tsx': $works_title_,
  },
  islands: {
    './islands/Header.tsx': $Header,
    './islands/Techs.tsx': $Techs,
    './islands/ThemeToggler.tsx': $ThemeToggler,
    './islands/Works.tsx': $Works,
    './islands/WorksSection.tsx': $WorksSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
