import { defineConfig } from '@twind/core';
import presetTailwind from '@twind/preset-tailwind';

export default defineConfig({
  presets: [presetTailwind()],
  theme: {
    colors: {
      'primary': '#2b5da7',
      'on-primary': '#ffffff',
      'primary-container': '#d6e3ff',
      'on-primary-container': '#001a40',
      'secondary': '#565f71',
      'on-secondary': '#ffffff',
      'secondary-container': '#dae2f8',
      'on-secondary-container': '#131c2c',
      'tertiary': '#705575',
      'on-tertiary': '#ffffff',
      'tertiary-container': '#fad7fd',
      'on-tertiary-container': '#28132e',
      'error': '#ba1b1b',
      'on-error': '#ffffff',
      'error-container': '#ffdad4',
      'on-error-container': '#410001',
      'background': '#fdfbff',
      'on-background': '#1a1b1f',
      'surface': '#fdfbff',
      'on-surface': '#1a1b1f',
      'surface-variant': '#e0e2ec',
      'on-surface-variant': '#44474f',
      'outline': '#74777f',
      'inverse-on-surface': '#f2f0f4',
      'inverse-surface': '#2f3034',
      'inverse-primary': '#a9c7ff',
      'shadow': '#000000',
      'bar': '#eceef8',
      'button-hover': '#2b5da714',
      // dark
      'primary-dark': '#a9c7ff',
      'on-primary-dark': '#002f68',
      'primary-container-dark': '#03458e',
      'on-primary-container-dark': '#d6e3ff',
      'secondary-dark': '#bec6dc',
      'on-secondary-dark': '#283041',
      'secondary-container-dark': '#3e4759',
      'on-secondary-container-dark': '#dae2f8',
      'tertiary-dark': '#ddbce0',
      'on-tertiary-dark': '#3f2844',
      'tertiary-container-dark': '#573e5c',
      'on-tertiary-container-dark': '#fad7fd',
      'error-dark': '#ffb4a9',
      'on-error-dark': '#680003',
      'error-container-dark': '#930006',
      'on-error-container-dark': '#ffdad4',
      'background-dark': '#1a1b1f',
      'on-background-dark': '#e3e2e6',
      'surface-dark': '#1a1b1f',
      'on-surface-dark': '#e3e2e6',
      'surface-variant-dark': '#44474f',
      'on-surface-variant-dark': '#c4c6d0',
      'outline-dark': '#8e9099',
      'inverse-on-surface-dark': '#1a1b1f',
      'inverse-surface-dark': '#e3e2e6',
      'inverse-primary-dark': '#2b5da7',
      'shadow-dark': '#000000',
      'bar-dark': '#252931',
      'button-hover-dark': '#a9c7ff14',
    },
    backgroundImage: {
      'profile':
        'linear-gradient(to bottom, #001a4066, #001a4066), url(/images/profile.jpg);',
    },
  },
});

export const configUrl = import.meta.url;
